name: Build and Push

on:
    push:
    workflow_dispatch:

jobs:
    build-directories:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.4.0
              with:
                  repository: "tianon/docker-postgres-upgrade"
            - id: set-matrix
              run: echo "::set-output name=matrix::$(ls | grep \\-to\\- | jq -R . | jq -cs .)"
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}
    build:
        runs-on: ubuntu-latest
        needs:
            - build-directories
        strategy:
            matrix:
                tag: ${{fromJson(needs.build-directories.outputs.matrix)}}
        steps:
            - uses: actions/checkout@v2.4.0
              with:
                  repository: "tianon/docker-postgres-upgrade"
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1.2.0
              with:
                  platforms: all
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1.6.0
              with:
                  version: latest
                  install: true
            - name: Login to DockerHub
              uses: docker/login-action@v1.10.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and push
              uses: docker/build-push-action@v2.9.0
              with:
                  context: .
                  file: ./${{ matrix.tag }}/Dockerfile
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: 1337kavin/postgres-upgrade:${{ matrix.tag }}
